# -*- coding: utf-8 -*-
"""ChatbotFormatting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12QujD9E9YWnDiX91GvEBYV1Hovt5cWig
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# 데이터 불러오기
df = pd.read_csv('/content/drive/MyDrive/24-1-nlp/chat_clean/preprocessed0610_participant.csv')
# df = pd.read_csv('/content/drive/MyDrive/24-1-nlp/chat_clean/preprocessed0610_500_participant.csv')

# 새로운 포맷의 데이터 저장 리스트
new_data = []
current_text = ""  # 현재까지의 누적 발화

# 대화 순서대로 처리
for index, row in df_full.iterrows():
    dialogue_id = row['dialogueID2']
    participant_id = row['participantID']
    utterance = row['utterance']

    # 대화 ID가 변경될 때마다 current_text 초기화
    if index == 0 or df_full.loc[index - 1, 'dialogueID2'] != dialogue_id:
        current_text = ""

    if participant_id == 'P01':
        # P01의 발화를 current_text에 추가
        current_text += " " + utterance if current_text else utterance
    elif participant_id == 'P02':
        # P02의 발화가 나올 때마다 new_data에 추가하고 current_text 업데이트
        new_data.append([current_text, utterance])
        current_text += " " + utterance

# 결과 데이터프레임 생성
new_df_full = pd.DataFrame(new_data_full, columns=['Text', 'Completion'])

# 새로운 포맷의 데이터 저장 리스트
new_data = []
current_text = ""  # 현재까지의 누적 발화

# 대화 순서대로 처리
for index, row in df.iterrows():
    dialogue_id = row['dialogueID2']
    participant_id = row['participantID']
    utterance = row['utterance']

    # 대화 ID가 변경될 때마다 current_text 초기화
    if index == 0 or df.loc[index - 1, 'dialogueID2'] != dialogue_id:
        current_text = ""

    if participant_id == 'P01':
        # P01의 발화를 current_text에 추가
        current_text += " " + utterance if current_text else utterance
    elif participant_id == 'P02':
        # P02의 발화가 나올 때마다 new_data에 추가하고 current_text 업데이트
        new_data.append([current_text, utterance])
        current_text += " " + utterance

# 결과 데이터프레임 생성
new_df = pd.DataFrame(new_data, columns=['Text', 'Completion'])

new_df_small = new_df[0:200001]

new_df_small.to_csv('/content/drive/MyDrive/24-1-nlp/chatbot/inputforchatbottrain_small.csv', index=False)
# new_df.to_csv('/content/drive/MyDrive/24-1-nlp/chatbot/inputforchatbottrain.csv', index=False)